import os

DISCOVERY_PORT = 4210
SERVER_PORT = int(os.getenv("KORANGU_SERVER_PORT", "8765"))
BEACON_MESSAGE = f"KORANGU_SERVER:{SERVER_PORT}".encode("utf-8")
BEACON_MESSAGE_LEGACY = b"KORANGU_SERVER"
DISCOVERY_MESSAGE = b"KORANGU_DISCOVER"
